# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1edc9f836f63daef055c15469efa3cccb3c95087a64371f8e26178bd1b2c58373450ec93de42ed12b3f2d6da87d47c9ecf3531ef886b3f1a75d14e4fd7ec22e5

test:
  secret_key_base: ecb3494be10962e9b0934eeba0562c80ddb6ef5a90f997719d65d87cf7f3dcbde30eb63803bef7ab51be45525b6b737a0aef64520b5895ab0e8f951f8faa1b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
